// prisma.config.ts tells Prisma's TOOLS where to FIND that schema file, where to STORE migration history, and — CRITICALLY — HOW to actually CONNECT to your real database (the connection STRING).

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv'
import { defineConfig } from "prisma/config"; //this FUNCTION's job is to take YOUR settings object and RETURN a properly FORMATTED Prisma configuration.

dotenv.config({
  path: './.env'
})

export default defineConfig({
  schema: "prisma/schema.prisma", //tells prisma where to find the schema
  migrations: { //auto-generated folder, tracking EVERY schema change you EVER make, over time (similar CONCEPT to a git commit HISTORY, but specifically for your DATABASE structure).
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL //this is where the actual database connection string lives
  },
});
